apiVersion: v1
data:
  application.properties: |-
    server.shutdown=graceful
    management.endpoints.web.exposure.include=*
kind: ConfigMap
metadata:
  name: {{ include "petclinic-helm.fullname" . }}